spring:
  datasource:
    url: jdbc:h2:mem:employee;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: changeIt
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /management

http:
  protocol: https

randomuser:
  hostname: randomuser.me